# Generated by Django 4.1.7 on 2023-04-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("central zone", "Central"),
                            ("south zone", "South"),
                            ("rural zone", "Countryside"),
                            ("unknown", "Undefined"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                ("is_open", models.BooleanField(default=False)),
            ],
        ),
    ]
